name: Documentation
on:
  push:
    branches: [main]
    tags: ['*']
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Hatch
        run: pip install --upgrade hatch
      - name: Deploy documentation
        run: hatch run docs:deploy